# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    app.filefactory.rootdir: /home/andrew/sites/test_symfony/site/web
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.filefactory:
        class: AppBundle\Service\FileFactory
        arguments: ['%app.filefactory.rootdir%']
